name: epitaph_v0
description: Epitaph Innovations

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  animated_theme_switcher: ^2.0.6
  cupertino_icons: ^1.0.2
  excel: ^2.0.0-null-safety-2
  flutter:
    sdk: flutter
  flutter_intro: ^3.0.2
  flutter_map: ^4.0.0
  geolocator: ^9.0.1
  is_first_run: ^1.0.0
  location: ^4.1.1
  overlay_tooltip: ^0.2.1
  positioned_tap_detector_2: ^1.0.4
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5
  video_player: ^2.2.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/blankProfile.png
    - assets/icons/noProfile.png
    - assets/icons/FB.png
    - assets/icons/IG.png
    - assets/icons/TW.png
    - assets/icons/close.png
    - assets/images/avatar.jpeg
    - assets/images/avatar_0.jpeg
    - assets/images/avatar_1.jpeg
    - assets/images/VetCemOutline.png
    - assets/images/VetCemOutline_17012023.png
    - assets/icons/A.png
    - assets/icons/B.png
    - assets/icons/C.png
    - assets/icons/D.png
    - assets/icons/E.png
    - assets/icons/F.png
    - assets/icons/Headstone.png
    - assets/icons/notch.png
    - assets/icons/logoOverlay.png
    - assets/icons/logoOverlay20x.png
    - assets/images/RKnutson-Cemetary.png
    - assets/images/header.png
    - assets/icons/history.png
    - assets/icons/welcome.png
    - assets/icons/locate.png
    - assets/icons/donate.png
    - assets/icons/story.png
    - assets/icons/thanks.png
    - assets/icons/aboutus.png
    - assets/icons/restroom.png
    - assets/files/
    - assets/screenshoots/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages